apiVersion: v2
name: istio
version: 0.0.0
type: application

dependencies:
  - name: base
    version: 1.28.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.28.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    version: 1.28.2
    repository: https://istio-release.storage.googleapis.com/charts

