apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httproute-jellyfin
spec:
  parentRefs:
  - name: gateway
    namespace: istio-ingress
  hostnames: ["jellyfin.k8s.labz"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: prod-jellyfin 
      port: 80
