apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-wildcard-tls
  namespace: istio-system
spec:
  secretName: root-ca-secret 
  duration: 2160h
  renewBefore: 720h
  dnsNames:
    - '*.k8s.labz'
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
