apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-wildcard-tls
  namespace: istio-system
spec:
  secretName: k8s-wildcard-secret
  duration: 90d
  renewBefore: 30d
  dnsNames:
    - '*.k8s.labz'
  issuerRef:
    name: root-ca
    kind: ClusterIssuer
