argo-cd:
  global:
    domain: argo.k8s.labz

  server:
    httproute:
      enabled: true
      parentRefs:
        - name: istio-gateway
          namespace: istio-system
          sectionName: https
